# backend/cloudbuild.yaml
steps:
  # 1. Bangun container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/alusista-backend:$COMMIT_SHA" # Tag dengan Commit SHA untuk versioning
      - "." # Konteks build adalah direktori saat ini (backend/)
    dir: "backend" # Jalankan perintah ini dari dalam direktori backend

  # 2. Push container image ke Google Container Registry (GCR) atau Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/alusista-backend:$COMMIT_SHA"]
    dir: "backend"

  # 3. Deploy image ke Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "alusista-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/alusista-backend:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated" # Sesuaikan jika perlu
      - "--set-env-vars"
      # - "^##^NODE_ENV=production##DB_USER=[YOUR_DB_USER]##DB_PASSWORD=[YOUR_DB_PASSWORD]##DB_NAME=[YOUR_DB_NAME]##CLOUD_SQL_CONNECTION_NAME=[YOUR_CLOUD_SQL_CONNECTION_NAME]"
      # - "--add-cloudsql-instances"
      # - "[YOUR_CLOUD_SQL_CONNECTION_NAME]"
images:
  - "gcr.io/$PROJECT_ID/alusista-backend:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
